name: Java CI with Maven

# 1. Kích hoạt (trigger) khi có sự kiện push hoặc pull_request
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    # 1. Cấu hình Matrix Strategy
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # 2. Thay vì fix cứng ubuntu, ta bảo GitHub chạy trên các HĐH trong ma trận
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt môi trường Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Build dự án với Maven
        run: mvn clean verify

      - name: Lưu trữ báo cáo Code Coverage (JaCoCo)
        if: always() # THÊM DÒNG NÀY: Ép chạy bước này ngay cả khi bước trên bị lỗi đỏ
        uses: actions/upload-artifact@v4
        with:
          name: JaCoCo-Report-${{ matrix.os }}
          path: target/site/jacoco/